site_name: EMBO Practical Course - Integrated multi-omic analyses of microbial communities
pages:
- Home: 'index.md'
- Day01 - The Why and the How:
    - Lecture AM: 'day01/multiomics_why.md'
    - Technical intro AM: 'technical_intro.md'
    - Hands-on PM: 'snakemake.md' 
- Day02 - Metagenomics:
    - Lecture AM: 'day02/concepts-history-next_steps-assembly.md'
    - Lecture and Hands-on PM: 'day02/binning.md'
- Day03 - Diversity & function:
    - Lecture and Hands-on AM: 'day03/taxonomy-gene_calling-annotation.md'
    - Hands-on PM: 'day03/phendb.md'
- Day04 - Functional omics:
    - Lecture and Hands-on AM: 'day04/metatranscriptomics.md'
    - Lecture AM: 'day04/metaproteomics.md'
    - Lecture PM: 'day04/biomolecular_extractions.md'
    - Hands-on PM: 'day04/metatranscriptomics_handson.md'
- Day05 - Metametabolomics:
    - Lecture AM: 'day05/intro_metabolomics.md'
    - Lecture and Hands-on AM: "day05/analytical_vasica-data_processing-metabolite_identification.md"
    - Hands-on PM: 'day05/metabolite_identification.md'
    - Lecture and Hands-on PM: 'day05/multi_omics-gene_centric_view.md'
    - Lecture and Hands-on PM: 'day05/multi_omics-genome_centric_view.md'
- Day06 - Multitrophic / Interkingdom interactions:
    - Lecture AM: 'day06/archaea.md'
    - Lecture AM: 'day06/microbe_host_interaction.md'
    - Lecture PM: 'day06/virus_host_interaction.md'
    - Hands-On PM: 'day06/vogdb_effectivedb.md'
- Day07 - Single-cell analyses and data integration:
    - Lecture AM: 'day07/single_cell.md'
    - Lecture and Hands-on PM: 'day07/normalisation_of_mda_data.md'
    - Hands-on PM: 'day07/multi_omic_data_integration.md'
- Day08 - Microbial ecology & network inference:
    - Lecture AM: 'day08/community_assembly_and_functioning.md'
    - Lecture AM: 'day08/inference_and_analysis_of_microbial_networks.md'
    - Hands-on AM: 'day08/inference_and_analysis_of_microbial_networks_applied.md'
theme: readthedocs
