site_name: EMBO Practical Course 2020 - Integrated multi-omic analyses of microbial communities

nav:
- Home: 'index.md'
- Preparation prior to the course: 'preparation.md'
- Day01 - The Why and the How:
    - Multi-omics - Why characterize other omes as well?!: 'day01/multiomics_why.md'
    - Technical Intro - Coursework folders, git, VMs etc: 'day01/technical_intro.md'
    - Snakemake - Hands-on: 'day01/nakemake.md' 
- Day02 - Metagenomics:
    - Metagenomics - Concepts, history, and next advances: 'day02/concepts-history-next_steps-assembly.md'
    - Binning of Metagenomic Data: 'day02/binning.md'
- Day03 - Diversity & function:
    - Taxonomy, phylogeny and diversity measures: 'day03/taxonomy-gene_calling-annotation.md'
    - De novo gene calling & annotation: 'day03/de_novo_gene_calling-annotation.md'
    - PhenDB: 'day03/phendb.md'
- Day04 - Functional omics:
    - Using metatranscriptomics to study active metabolic pathways in situ: 'day04/metatranscriptomics.md'
    - Metaproteomics - sequences and masses: 'day04/metaproteomics.md'
    - Biomolecular extraction for integrative multi-omics: 'day04/biomolecular_extractions.md'
    - Using metaproteomics to study microbial activity in situ - Hands-on: 'day04/metatranscriptomics_handson.md'
- Day05 - Metametabolomics:
    - Introduction to Metabolomics: 'day05/intro_metabolomics.md'
    - Analytical Basics, Data-Processing and Metabolite Identification in Metabolomics: 'day05/analytical_vasica-data_processing-metabolite_identification.md'
    - Metabolite Identification: 'day05/metabolite_identification.md'
    - Multi-omics integration - amplicon-seq & metabolomics: 'day05/amplicon_seq-metabolomics.md'
    - Multi-omics integration - genome scale metabolic models: 'day05/multi_omics-genome_centric_view.md'
- Day06 - Multitrophic / Interkingdom interactions:
    - Archaea and microbe/host interactions: 'day06/archaea.md'
    - Microbe and Host interaction, EffectiveDB: 'day06/microbe_host_interaction.md'
    - Virus and Host interaction, VogDB: 'day06/virus_host_interaction.md'
- Day07 - Single-cell analyses and data integration:
    - Single-cell resolution of mixed microbial communities: 'day07/single_cell.md'
    - Normalisation of MDA data: 'day07/normalisation_of_mda_data.md'
    - Multi-Omic Data Integration in R: 'day07/multi_omic_data_integration.md'
    - Multi-omics integration - gene centric view: 'day05/multi_omics-gene_centric_view.md'
- Day08 - Microbial ecology & network inference:
    - Community assembly and functioning in microbial ecology: 'day08/community_assembly_and_functioning.md'
    - Inference and analysis of microbial networks: 'day08/inference_and_analysis_of_microbial_networks.md'
    - Inference and analysis of microbial networks - Hands-on: 'day08/inference_and_analysis_of_microbial_networks_applied.md'

theme: 
    name: readthedocs
    custom_dir: embo2020_theme/

markdown_extensions:
    - toc:
        toc_depth: 2
